// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TarantoolCluster) DeepCopyInto(out *TarantoolCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TarantoolCluster.
func (in *TarantoolCluster) DeepCopy() *TarantoolCluster {
	if in == nil {
		return nil
	}
	out := new(TarantoolCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TarantoolCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TarantoolClusterList) DeepCopyInto(out *TarantoolClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TarantoolCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TarantoolClusterList.
func (in *TarantoolClusterList) DeepCopy() *TarantoolClusterList {
	if in == nil {
		return nil
	}
	out := new(TarantoolClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TarantoolClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TarantoolClusterSpec) DeepCopyInto(out *TarantoolClusterSpec) {
	*out = *in
	in.ReplicasetTemplate.DeepCopyInto(&out.ReplicasetTemplate)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TarantoolClusterSpec.
func (in *TarantoolClusterSpec) DeepCopy() *TarantoolClusterSpec {
	if in == nil {
		return nil
	}
	out := new(TarantoolClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TarantoolClusterStatus) DeepCopyInto(out *TarantoolClusterStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TarantoolClusterStatus.
func (in *TarantoolClusterStatus) DeepCopy() *TarantoolClusterStatus {
	if in == nil {
		return nil
	}
	out := new(TarantoolClusterStatus)
	in.DeepCopyInto(out)
	return out
}
