// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"gitlab.com/tarantool/sandbox/tarantool-operator/pkg/apis/tarantool/v1alpha1.TarantoolCluster":       schema_pkg_apis_tarantool_v1alpha1_TarantoolCluster(ref),
		"gitlab.com/tarantool/sandbox/tarantool-operator/pkg/apis/tarantool/v1alpha1.TarantoolClusterSpec":   schema_pkg_apis_tarantool_v1alpha1_TarantoolClusterSpec(ref),
		"gitlab.com/tarantool/sandbox/tarantool-operator/pkg/apis/tarantool/v1alpha1.TarantoolClusterStatus": schema_pkg_apis_tarantool_v1alpha1_TarantoolClusterStatus(ref),
	}
}

func schema_pkg_apis_tarantool_v1alpha1_TarantoolCluster(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TarantoolCluster is the Schema for the tarantoolclusters API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("gitlab.com/tarantool/sandbox/tarantool-operator/pkg/apis/tarantool/v1alpha1.TarantoolClusterSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("gitlab.com/tarantool/sandbox/tarantool-operator/pkg/apis/tarantool/v1alpha1.TarantoolClusterStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"gitlab.com/tarantool/sandbox/tarantool-operator/pkg/apis/tarantool/v1alpha1.TarantoolClusterSpec", "gitlab.com/tarantool/sandbox/tarantool-operator/pkg/apis/tarantool/v1alpha1.TarantoolClusterStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_tarantool_v1alpha1_TarantoolClusterSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TarantoolClusterSpec defines the desired state of TarantoolCluster",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_tarantool_v1alpha1_TarantoolClusterStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TarantoolClusterStatus defines the observed state of TarantoolCluster",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
